### ISSUE TITLE
Linux: server is for low pings only

### ISSUE THREAD

**Issue by Yuego** [FrozenSand/ioq3-for-UrbanTerror-4#23]
If the server is set sv_maxping, you can not connect to the server.

My ping is between 80-100, but I can not connect to the servers where sv_maxping is set. I tried to connect to servers with sv_maxping = 150, 200, 300 - always a failure.

If sv_maxping is not set, no problems with the connection.

URT 4.2.012

**Comment by Barbatos** [comment]
Closing this old ticket, iirc it doesn't happen anymore and was fixed a long time ago. Please do not hesitate to reopen if needed.
