### ISSUE TITLE
Engine versioning

### ISSUE THREAD

**Issue by danielepantaleone** [FrozenSand/ioq3-for-UrbanTerror-4#62]
Would it be possibile to use GitHub releases to upload the compiled version of the engine instead of uploading them into a directory in the Git repo? In this way each release will be linked to a Git tag and the compiled version of each platform engine will be versioned.

**Comment by Barbatos** [comment]
All engine versions are already versioned this way but I agree that adding engine binaries to the repository files sucks. iirc we did this at a time GitHub didn't offer attaching binary/zip files to releases. 

I'll look into it for future releases!

**Comment by ThomasBrierley** [comment]
:+1: Would stop the repo from growing so big too.

**Comment by Barbatos** [comment]
Binary files are now included in the releases and were removed from the repository as of the 4.3.3 release.
