### ISSUE TITLE
Can not build on debug mode

### ISSUE THREAD

**Issue by pedrxd** [FrozenSand/ioq3-for-UrbanTerror-4#65]
I try to build the engine as debug mode, but is not possible due some error on the botlib:

  Output:
    build/debug-linux-x86_64/Quake3-UrT-Ded.x86_64
    build/debug-linux-x86_64/Quake3-UrT.x86_64

make[2]: se entra en el directorio '/simpledirectory/ioq3-for-UrbanTerror-4'
LD build/debug-linux-x86_64/Quake3-UrT-Ded.x86_64
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_TravelFlagForType':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:192: referencia a `AAS_TravelFlagForType_inline' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_FreeOldestCache':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:716: referencia a `AAS_ClusterAreaNum' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_ReadRouteCache':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1116: referencia a `AAS_ClusterAreaNum' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_UpdateAreaRoutingCache':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1315: referencia a `AAS_ClusterAreaNum' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1350: referencia a `AAS_TravelFlagForType_inline' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1354: referencia a `AAS_AreaContentsTravelFlags_inline' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1362: referencia a `AAS_ClusterAreaNum' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_GetAreaRoutingCache':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1410: referencia a `AAS_ClusterAreaNum' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1439: referencia a `AAS_RoutingTime' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_UpdatePortalRoutingCache':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1503: referencia a `AAS_ClusterAreaNum' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_GetPortalRoutingCache':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1579: referencia a `AAS_RoutingTime' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_AreaRouteToGoalArea':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1673: referencia a `AAS_ClusterAreaNum' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1730: referencia a `AAS_ClusterAreaNum' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_PredictRoute':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1837: referencia a `AAS_TravelFlagForType_inline' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1842: referencia a `AAS_TravelFlagForType_inline' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1846: referencia a `AAS_AreaContentsTravelFlags_inline' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1851: referencia a `AAS_AreaContentsTravelFlags_inline' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:1895: referencia a `AAS_TravelFlagForType_inline' sin definir
build/debug-linux-x86_64/ded/be_aas_route.o: En la función `AAS_NearestHideArea':
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:2139: referencia a `AAS_TravelFlagForType_inline' sin definir
/simpledirectory/ioq3-for-UrbanTerror-4/code/botlib/be_aas_route.c:2141: referencia a `AAS_AreaContentsTravelFlags_inline' sin definir
collect2: error: ld returned 1 exit status
Makefile:1441: fallo en las instrucciones para el objetivo 'build/debug-linux-x86_64/Quake3-UrT-Ded.x86_64'
make[2]: *** [build/debug-linux-x86_64/Quake3-UrT-Ded.x86_64] Error 1
make[2]: se sale del directorio '/simpledirectory/ioq3-for-UrbanTerror-4'
Makefile:986: fallo en las instrucciones para el objetivo 'targets'
make[1]: *** [targets] Error 2
make[1]: se sale del directorio '/simpledirectory/ioq3-for-UrbanTerror-4'
Makefile:974: fallo en las instrucciones para el objetivo 'debug'
make: *** [debug] Error 2

**Comment by Barbatos** [comment]
Closing this old ticket, compilation works fine on CentOS / Debian / Ubuntu / Windows [7,10] / OSX >= 10.6 as of today. If you still encounter issues, please do not hesitate to reopen + specify your Linux distribution.
