### ISSUE TITLE
Crash on launch on Mac OS

### ISSUE THREAD

**Issue by iosdevben** [FrozenSand/ioq3-for-UrbanTerror-4#83]
The game refuses to start sometimes on Mac OS. I'm on Mac OS 11.1.

The console shows the following messages:

default	06:47:48.490871+1100	Quake3-UrT.x86_64	WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.0 instead of 10.16.0. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
default	06:47:48.491060+1100	Quake3-UrT.x86_64	0   CarbonCore                          0x00007fff2281887a ___Gestalt_SystemVersion_block_invoke + 112
default	06:47:48.491106+1100	Quake3-UrT.x86_64	1   libdispatch.dylib                   0x00007fff201847c7 _dispatch_client_callout + 8
default	06:47:48.491138+1100	Quake3-UrT.x86_64	2   libdispatch.dylib                   0x00007fff2018596b _dispatch_once_callout + 20
default	06:47:48.491156+1100	Quake3-UrT.x86_64	3   CarbonCore                          0x00007fff227ba2ce _Gestalt_SystemVersion + 941
default	06:47:48.491189+1100	Quake3-UrT.x86_64	4   CarbonCore                          0x00007fff227b9ee7 Gestalt + 149
default	06:47:48.491209+1100	Quake3-UrT.x86_64	5   libSDL-1.2.0.dylib                  0x0000000100d99a3b QZ_VideoInit + 43
default	06:47:48.491225+1100	Quake3-UrT.x86_64	6   libSDL-1.2.0.dylib                  0x0000000100d9183b SDL_VideoInit + 555

This has happened from time to time over the past few years, and I can usually get the game to launch eventually by changing my screen resolution - coz my theory is that will "reset" something, but today it's not helping.

**Comment by MaddTheSane** [comment]
That specific warning shouldn't cause a crash. What I get on my M1 MacBook Pro is:

````
GL_VENDOR: Apple
GL_RENDERER: Apple M1
GL_VERSION: 2.1 Metal - 71.0.7
GL_MAX_TEXTURE_SIZE: 16384
GL_MAX_ACTIVE_TEXTURES_ARB: 8

PIXELFORMAT: color(32-bits) Z(24-bit) stencil(8-bits)
MODE: 8, 1280 x 1024 fullscreen hz:N/A
GAMMA: hardware w/ 0 overbright bits
CPU: 
rendering primitives: multiple glArrayElement
texturemode: GL_LINEAR_MIPMAP_NEAREST
picmip: 1
texture bits: 32
multitexture: enabled
compiled vertex arrays: disabled
texenv add: enabled
compressed textures: disabled
SDL_SetGammaRamp: Received signal 11, exiting...
----- CL_Shutdown -----
RE_Shutdown( 1 )
````

I don't know why anything in the gamma ramp code that would cause a signal 11 to be sent during it. Maybe the version of SDL used is outdated. Based off of Urban Terror 4.3.4.

**Comment by iosdevben** [comment]
To be clear, I can not run the game due to this bug, unless I disable gamma via the autoexec, but some maps are unplayable with standard gamma.
